"""empty message

Revision ID: 06c68378856b
Revises: 
Create Date: 2023-01-30 16:23:42.439890

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06c68378856b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('doctor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=140), nullable=False, unique=True),
    sa.Column('name', sa.String(length=140), nullable=False),
    sa.Column('password', sa.String(length=140), nullable=False),
    sa.Column('firmadig', sa.String(length=140), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('patient',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('firstname', sa.String(length=64), nullable=True),
    sa.Column('lastname', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('address', sa.String(length=128), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=140), nullable=True),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('message', sa.String(length=2000), nullable=True),  
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_patient_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_patient_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_patient_firstname'), ['firstname'], unique=True)
        batch_op.create_index(batch_op.f('ix_patient_lastname'), ['lastname'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_patient_lastname'))
        batch_op.drop_index(batch_op.f('ix_patient_firstname'))
        batch_op.drop_index(batch_op.f('ix_patient_email'))
        batch_op.drop_index(batch_op.f('ix_patient_date'))

    op.drop_table('patient')
    op.drop_table('doctor')
    op.drop_table('messages')
    # ### end Alembic commands ###
